services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - .:/app/:rw
    networks:
      - academia-backend-services
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    # command: [
    #   "--replSet", "rs0",
    #   "--bind_ip_all",
    #   "--keyFile", "/etc/mongo-keyfile"
    # ]
    command: [
      "bash", "-c",
      "cp /etc/mongo-keyfile /tmp/keyfile && chmod 400 /tmp/keyfile && exec mongod --replSet rs0 --bind_ip_all --keyFile /tmp/keyfile"
    ]
    networks:
      - academia-backend-services

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo
    volumes:
      - ./scripts/init-replica.sh:/init-replica.sh
    env_file:
      - .env
    entrypoint: ["bash", "/init-replica.sh"]
    networks:
      - academia-backend-services

  mongo-express:
    image: mongo-express:latest
    ports:
      - "${ME_PORT}:${ME_PORT}"
    env_file:
      - .env
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_URI}
      - PORT=${ME_PORT}
    networks:
      - academia-backend-services
    depends_on:
      - mongo

  typesense:
    image: typesense/typesense:29.0.rc30
    restart: on-failure
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    volumes:
      - ./data:/data
    networks:
      - academia-backend-services

volumes:
  mongo-data:
    external: false

networks:
  academia-backend-services:
    external: false